use std::{
    env,
    fs,
    path::PathBuf,
};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let repo_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("workspace root")
        .to_path_buf();
    let js_path = repo_root.join("test").join("generate_pinyin_syllables.js");

    println!("cargo:rerun-if-changed={}", js_path.display());

    let js = fs::read_to_string(&js_path).expect("read generate_pinyin_syllables.js");
    let entries = parse_syllabary(&js);
    if entries.is_empty() {
        panic!("failed to parse syllabary from {}", js_path.display());
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let out_rs = out_dir.join("syllabary_gen.rs");
    fs::write(&out_rs, render_rust(&entries)).expect("write syllabary_gen.rs");
}

fn parse_syllabary(js: &str) -> Vec<(String, i32)> {
    let mut out = Vec::new();
    let mut in_obj = false;
    for line in js.lines() {
        let line = line.trim();
        if line.starts_with("const syllabary") && line.contains('{') {
            in_obj = true;
            continue;
        }
        if in_obj && line.starts_with("};") {
            break;
        }
        if !in_obj {
            continue;
        }
        // 形如：a: 45,
        let Some((k, v)) = line.split_once(':') else {
            continue;
        };
        let key = k.trim();
        if key.is_empty() || !key.bytes().all(|b| b.is_ascii_lowercase()) {
            continue;
        }
        let v = v.trim().trim_end_matches(',').trim();
        let Ok(freq) = v.parse::<i32>() else {
            continue;
        };
        out.push((key.to_string(), freq));
    }
    out
}

fn render_rust(entries: &[(String, i32)]) -> String {
    let mut s = String::new();
    s.push_str("// @generated by rime_pinyin/build.rs\n");
    s.push_str("pub const SYLLABARY: &[(&str, i32)] = &[\n");
    for (k, v) in entries {
        s.push_str(&format!("    (\"{k}\", {v}),\n"));
    }
    s.push_str("];\n");
    s
}


